from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from pymongo import MongoClient
from datetime import datetime
from enum import Enum
import os
import uvicorn

# Connection to MongoDB
MONGO_URI = "mongodb+srv://museomagazzino:artwork@cluster0.kedecnn.mongodb.net/?appName=Cluster0"
client = MongoClient(MONGO_URI)
db = client["MuseoMagazzino"]
artworks_collection = db["artworks"]
iot_collection = db["iot-data"]

app = FastAPI(title="Museum Smart System API")

# ==========================
# MODELS
# ==========================

class StatusEnum(str, Enum):
    storehouse = "storehouse"
    inShipment = "inShipment"
    museum = "museum"


class ArtWork(BaseModel):
    _id: str
    artName: str
    artistName: str
    year: int
    status: StatusEnum   # storehouse / inShipment / museum
    loanedTo: str = ""   # Museo's name or empty string

class IoTData(BaseModel):
    id: str  
    latitude: float
    longitude: float
    temperature: float
    humidity: float
    timestamp: str

    class Config:
        fields = {"id": "_id"}

# ==========================
# ENDPOINT ART WORKS
# ==========================

@app.get("/artworks")
def get_all_artworks():
    data = list(artworks_collection.find({}))
    artworks_list = []

    for item in data:
        artworks_list.append({
            "_id": str(item["_id"]),             # ObjectId -> stringa
            "artName": item.get("artName", ""),
            "artistName": item.get("artistName", ""),
            "year": item.get("year", 0),
            "status": item.get("status", "storehouse"),  # storehouse / inShipment / museum
            "loanedTo": item.get("loanedTo", "")
        })

    return {"count": len(artworks_list), "artworks": artworks_list}


@app.post("/artworks/add")
def add_artwork(artwork: ArtWork):
    """Add new artwork"""
    if artworks_collection.find_one({"_id": artwork._id}):
        raise HTTPException(status_code=400, detail="This artWork is already in the db")
    artworks_collection.insert_one(artwork.dict())
    return {"message": f"The artwork: '{artwork.name}'was added!"}

@app.delete("/artworks/{artwork_id}")
def delete_artwork(artwork_id: str):
    """Remove artwork"""
    result = artworks_collection.delete_one({"_id": artwork_id})
    if result.deleted_count == 0:
        raise HTTPException(status_code=404, detail="This artwork isn't in the db")
    return {"message": f"The artwork: {artwork_id} was removed from db"}

# ==========================
#  ENDPOINT IoT
# ==========================

@app.get("/iot-data")
def get_iot_data():
    """Get all the iot datas"""
    data = list(iot_collection.find({}, {"_id": 0}))  # exclude the _id ObjectId generated by MongoDB
    return {"count": len(data), "iot_data": data}

@app.post("/iot-data/update")
def update_iot_data(data: IoTData):
    """Update iot for all the artworks"""
   
    artwork = artworks_collection.find_one({"_id": data.id})

    if not artwork:
        raise HTTPException(status_code=404, detail=f"The artwork: {data.id} doesn't exist")

    try:
        # Update or insert iot data
        iot_collection.update_one(
            {"_id": data.id},
            {"$set": data.dict(by_alias=True)},
            upsert=True
        )
        return {"message": f"Updated for {data.id}"}
    except Exception as e:
        print("Error during the update", e)
        raise HTTPException(status_code=500, detail="Internal error during update")


# ==========================
# TEST ROUTE
# ==========================

@app.get("/")
def root():
    return {"message": "Museum Smart System API actived"}

# ==========================
# START SERVER
# ==========================

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8000))  # that is for render
    uvicorn.run("main:app", host="0.0.0.0", port=port)
